language: ruby
rvm:
 - "2.0.0"
 - "2.2.0"

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

script:
  - bundle exec rake --trace db:migrate test
  - bundle exec rspec spec

before_script:
  - psql -c 'create database datalab_api_test' -U postgres
