language: ruby
rvm:
 - "2.0.0"
 - "2.2.0"

env:
  - DB=postgresql

script:
  - bundle exec rake --trace db:create test
  - bundle exec rake --trace db:migrate test
  - bundle exec rspec spec

before_script:
  - psql -c 'create database datalab_api_test' -U postgres
  - psql datalab_api_test -c 'create extension hstore;' -U postgres

addons:
    code_climate:
        repo_token: bc22c18f4dd71194456c95d355cc1e028166c105a5d307ddc05c1990dbba148c