language: ruby
rvm:
 - "2.0.0"
 - "2.2.0"

addons:
  postgresql: "9.3"

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml

script: "bundle exec rspec spec"

addons:
    code_climate:
        repo_token: ccc8d7773568a3153abc015f4cc8ae7e16ddabdfc106d5ad77c03f675184e113