
sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3 

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  database: datalab_api_<%= Rails.env %>

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
