defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  adapter: postgresql
  username: postgres
  database: datalab_api_<%= Rails.env %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults